name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: pwd && cd /home/runner/work/rundeck/rundeck/docker/offical &&docker build . --file Dockerfile --tag my-image-name:$(date +%s)
